### PR TITLE
Task

### PR DESCRIPTION
**Pull request by sab115**
- add, edit, and delete (soft delete) tasks functionality
- trash bin: recovered or permanently delete, and empty trash bin(followed with a Confirmation Popup Window)
- Tooltips

Implemented add, edit, and delete (soft delete) tasks functionality. Also created a trash bin to implement soft delete. Deleted tasks in the trash bin could be recovered or permanently deleted, also there's an empty trash bin function with a ConfirmDeleteModal to permanently delete all tasks and prevent the users from accidentally emptying the trash in the trash bin. Added Tooltips component to provide users hints to identify what functionality is connected to the icons. Also created components for Categories and Category(card).

### CODE REVIEW

**Review by aryaramchander1 — COMMENTED** [review]
This looks great! I like how your code is well formatted with good spacing. I think adding some more descriptive comments will make the code easier to follow - maybe be more specific in terms of what each block of code exactly does, in a bit more detail. Other than that, looks good!

**Review by emlai1263 — APPROVED** [review]
I noticed that you have what looks like old versions of functions commented out in EditTask.js, TrashBin.js, and Dashboard.js. Since your trash feature sis working now, I think you can delete these. Everything else looks good! I like how organized everything is through individual classes and components.

**Comment by sab115** [comment]
> This looks great! I like how your code is well formatted with good spacing. I think adding some more descriptive comments will make the code easier to follow - maybe be more specific in terms of what each block of code exactly does, in a bit more detail. Other than that, looks good!

Okay, I'll add some more comments to help ease the readability of the code!

**Comment by sab115** [comment]
> > This looks great! I like how your code is well formatted with good spacing. I think adding some more descriptive comments will make the code easier to follow - maybe be more specific in terms of what each block of code exactly does, in a bit more detail. Other than that, looks good!
> 
> Okay, I'll add some more comments to help ease the readability of the code!

Updated!

**Pull request merged**
